
name: build-test
on: push

jobs:
  build:
    name: build examples
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.14.0
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: build examples
        run: find ./examples -type f -name "main.go" | xargs -Ip tinygo build -o p.wasm -target=wasm -wasm-abi=generic p

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: run tests
        run: go test -tags=proxytest -v -race ./...
