name: build-test
on: push

jobs:
  sdk-tests:
    name: sdk tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run golangci-lint
        uses: docker://golangci/golangci-lint:v1.31.0
        with:
          args: make lint

      - name: set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: run tests
        run: make test.sdk

  build-examples:
    name: build examples
    runs-on: ubuntu-latest
    container:
      image: getenvoy/extension-tinygo-builder:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build examples
        run: make build.examples

      - name: upload wasm-binaries
        uses: actions/upload-artifact@v2
        with:
          name: wasm-binaries
          path: examples

  e2e-tests:
    strategy:
      matrix:
        istio-version: [ 1.7.0, 1.7.1, 1.7.2 ]
    name: e2e tests on examples
    needs: build-examples
    runs-on: ubuntu-latest
    container:
      image: getenvoy/proxy-wasm-go-sdk-ci:istio-${{ matrix.istio-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: download wasm-binaries
        uses: actions/download-artifact@v2
        with:
          name: wasm-binaries
          path: examples

      - name: run e2e test
        run: go test ./e2e/... -v
